#include "main.h"
#include "gba.h"
#include "game.h"
#include <stdio.h>
#include <stdlib.h>


//!! INCLUDE IMAGE FILENAMES HERE !!//
#include "images/TitleScreen.h"
#include "images/FinalScoreScreen.h"
#include "images/GameOverScreen.h"
#include "images/apple.h"
#include "images/bananas.h"
#include "images/orange.h"
#include "images/grapes.h"
#include "images/pear.h"
#include "images/bomb.h"
#include "images/Lbasket.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  while (1) {
    struct GameState state;

    //Draw start screen
    startGame(&state);
    drawStartScreen();
    while(1) {
      u32 currentButtons = BUTTONS;
      waitForVBlank();
      if (KEY_DOWN(BUTTON_START, currentButtons)) {
        break;
      }
      if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
        continue;
      }
    }
    while (!state.gameOver) {
      u32 currentButtons = BUTTONS;
      waitForVBlank();
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        break;
      }
      updateGame(&state, currentButtons);
      drawGame(&state);
    }
    waitForVBlank();
    //Screen Display 
    if (state.endGameType == 1) {
      //End game b/c bomb
      drawGameOverScreen();
    } else if (state.endGameType == 2) {
      //End game b/c timer
      drawFinalScoreScreen(&state);
    }
    waitForVBlank();
    while (!KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
      waitForVBlank();
      if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
        break;
      }
    }
  }
  return 0;
   // currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    /*switch (state) {
      case START:

        // state = ?
        break;
      case PLAY:

        // state = ?
        break;
      case WIN:

        // state = ?
        break;
      case LOSE:

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used */
}